/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectogrupalfinal;

import com.sun.media.sound.AuFileReader;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David Andres
 */
public class GuiProyectoFinal extends javax.swing.JFrame {
                ImageIcon imageBMW= new ImageIcon("BMW-Logo.png"); 
                ImageIcon imageHYDAI = new ImageIcon ("logoHYUNDAI.png");
                ImageIcon imageMercedes= new ImageIcon ("Mercedes-Logo-2009–now1.png");
                ImageIcon imagen= new ImageIcon("MERCEDES-BENZ-CLASSE-B-00.jpg"); 
                ImageIcon imagen1= new ImageIcon("450_1000.jpg"); 
                ImageIcon imagen2= new ImageIcon("BMW7.png"); 
                ImageIcon imagen3= new ImageIcon("bmw-m3-e46-gtr-p.jpg"); 
                ImageIcon imagen4= new ImageIcon("descarga.jfif");
                ImageIcon imagen5= new ImageIcon("descarga (1).jfif"); 

       Factura e1= new Factura();
       Fecha c1;
       
       
       
    /**
     * Creates new form GuiProyectoFinal
     */
    public GuiProyectoFinal() {
    
        initComponents();
        
        e1 = new Factura();
         
    }
    Automovil auto[] = new Automovil[6];
    
    public void crearAutomivil(){
        auto[0] = new Automovil("Mercedes Benzs Clase B B 180D","SUV crossover","Mercedes Benz",28.462,2013,190);
        auto[1] = new Automovil("Mercedes Benzs GLA","SUV compacto","Mercedes Benz",40.800,2014,210);
        auto[2] = new Automovil("BMW Serie 7","Sedán","BMW",101.400,2019,250);
        auto[3] = new Automovil("BMW GRT M3","Coupé","BMW",55.000,2006,260);
        auto[4] = new Automovil("Accent","Sedán","Hyundai",45.900,2018,190);
        auto[5] = new Automovil("Verna","Subcompacto","Hyundai",18.250,2020,170);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgMarca = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rbtMercedes = new javax.swing.JRadioButton();
        rbtBMW = new javax.swing.JRadioButton();
        rbtHyundai = new javax.swing.JRadioButton();
        cmbColor = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        lblMercedes = new javax.swing.JLabel();
        lblBMW = new javax.swing.JLabel();
        lblHyudai = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbmMercedes = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cbmBMW = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cmbHyundai = new javax.swing.JComboBox<>();
        lblAuto = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        btnInformacion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaInformacion = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblDateExample = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Empleado"));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Codigo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos del vehiculo"));

        jLabel9.setText("Marca :");

        jLabel10.setText("Color:");

        btgMarca.add(rbtMercedes);
        rbtMercedes.setText("Mercedes Benzs");
        rbtMercedes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtMercedesMouseClicked(evt);
            }
        });
        rbtMercedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMercedesActionPerformed(evt);
            }
        });

        btgMarca.add(rbtBMW);
        rbtBMW.setText("BMW");
        rbtBMW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtBMWMouseClicked(evt);
            }
        });
        rbtBMW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtBMWActionPerformed(evt);
            }
        });

        btgMarca.add(rbtHyundai);
        rbtHyundai.setText("Hyundai");
        rbtHyundai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtHyundaiMouseClicked(evt);
            }
        });
        rbtHyundai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtHyundaiActionPerformed(evt);
            }
        });

        cmbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Rojo", "Blanco", "Negro", "Gris" }));

        jLabel12.setText("Características:");

        lblMercedes.setText(".");

        lblBMW.setText(".");

        lblHyudai.setText(".");

        jLabel13.setText("Modelos:");

        jLabel14.setText("Mercedes Benzs:");

        cbmMercedes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Mercedes Benzs Clase B B 180D", "Mercedes Benzs GLA" }));
        cbmMercedes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmMercedesItemStateChanged(evt);
            }
        });
        cbmMercedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmMercedesActionPerformed(evt);
            }
        });

        jLabel15.setText("BMW:");

        cbmBMW.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "      ", "BMW Serie 7", "BMW GRT M3" }));
        cbmBMW.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmBMWItemStateChanged(evt);
            }
        });

        jLabel16.setText("Hyundai:");

        cmbHyundai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Accent", "Verna" }));
        cmbHyundai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbHyundaiItemStateChanged(evt);
            }
        });

        lblAuto.setText(".");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel13))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbmMercedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(cbmBMW, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(cmbHyundai, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbmMercedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cbmBMW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(cmbHyundai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblAuto, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnInformacion.setText("Información");
        btnInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionActionPerformed(evt);
            }
        });

        txaInformacion.setColumns(20);
        txaInformacion.setRows(5);
        jScrollPane2.setViewportView(txaInformacion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(lblMercedes))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(rbtMercedes)))
                        .addGap(182, 182, 182)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBMW)
                            .addComponent(rbtBMW, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(171, 171, 171)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHyudai)
                            .addComponent(rbtHyundai, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(42, 42, 42)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMercedes)
                    .addComponent(lblBMW)
                    .addComponent(lblHyudai))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtBMW)
                    .addComponent(rbtMercedes)
                    .addComponent(rbtHyundai))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnInformacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnComprar)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Cliente"));

        jLabel4.setText("Nombre:");

        jLabel5.setText("Apellido:");

        jLabel6.setText("Cedula:");

        jLabel7.setText("Edad:");

        jLabel11.setText("Fecha:");

        lblDateExample.setText("DD/MM/AAAA");
        lblDateExample.setToolTipText("");
        lblDateExample.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCedula))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDateExample))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addComponent(jLabel8)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblDateExample)))
                .addContainerGap())
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnGuardar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void cbmMercedesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmMercedesItemStateChanged
        //int img = cbmMercedes.getSelectedIndex();
        Integer indice = cbmMercedes.getSelectedIndex();
        if (indice.equals(0))
        {
            lblAuto.setIcon(null);

        }
        else if (indice.equals(1))
        {
            lblAuto.setIcon(imagen);

        }
        else
        lblAuto.setIcon(imagen1);

        // TODO add your handling code here:
    }//GEN-LAST:event_cbmMercedesItemStateChanged

    private void cbmMercedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmMercedesActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cbmMercedesActionPerformed

    private void cbmBMWItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmBMWItemStateChanged
        Integer indice = cbmBMW.getSelectedIndex();
        if (indice.equals(0))
        {
            lblAuto.setIcon(null);

        }
        else if (indice.equals(1))
        {
            lblAuto.setIcon(imagen2);

        }
        else
        lblAuto.setIcon(imagen3);

        // TODO add your handling code here:
    }//GEN-LAST:event_cbmBMWItemStateChanged

    private void cmbHyundaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbHyundaiItemStateChanged

        Integer indice = cmbHyundai.getSelectedIndex();
        if (indice.equals(0))
        {
            lblAuto.setIcon(null);

        }
        else if (indice.equals(1))
        {
            lblAuto.setIcon(imagen4);

        }
        else
        lblAuto.setIcon(imagen5);
//
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbHyundaiItemStateChanged

    private void rbtMercedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMercedesActionPerformed
        lblMercedes.setIcon(imageMercedes);          
    }//GEN-LAST:event_rbtMercedesActionPerformed

    private void rbtBMWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtBMWActionPerformed
        lblBMW.setIcon(imageBMW);         // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtBMWActionPerformed

    private void rbtHyundaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtHyundaiActionPerformed
        lblHyudai.setIcon(imageHYDAI);         

        // TODO add your handling code here:
    }//GEN-LAST:event_rbtHyundaiActionPerformed

    private void btnInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionActionPerformed
        // TODO add your handling code here:
        
        String aux,aux1,aux2;
        crearAutomivil();

        try{
            
            if(rbtBMW.isSelected()){
               aux = (String) cbmBMW.getSelectedItem();
                if(aux.equals("BMW Serie 7")){
                    txaInformacion.setText(auto[2].toString());
                }
                if(aux.equals("BMW GRT M3")){
                    txaInformacion.setText("");
                    txaInformacion.setText(auto[3].toString());
                }              
            }
            if(rbtHyundai.isSelected()){
                aux = (String) cmbHyundai.getSelectedItem();
                if(aux.equals("Accent")){
                   txaInformacion.setText(auto[4].toString()); 
                }
                if(aux.equals("Verna")){
                    txaInformacion.setText(auto[5].toString());
                }
            }
            if(rbtMercedes.isSelected()){
                aux = (String) cbmMercedes.getSelectedItem();
                if(aux.equals("Mercedes Benzs Clase B B 180D")){
                    txaInformacion.setText(auto[0].toString());
                }
                if(aux.equals("Mercedes Benzs GLA")){
                    txaInformacion.setText(auto[1].toString());
                }
            }
                
        }
        catch(Exception e){
           JOptionPane.showConfirmDialog(rootPane, "ERROR");
        }
      
    }//GEN-LAST:event_btnInformacionActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
        
        GUIFactura obj1 =  new GUIFactura();
       obj1.setVisible(true);
       this.dispose();
GUIFactura.txtnombeven.setText(txtNombre.getText());
GUIFactura.txtapellv.setText(txtApellido.getText());
GUIFactura.txtcodigv.setText(txtCodigo.getText());
GUIFactura.txtNombcom.setText(txtNombre1.getText());
GUIFactura.txtapellidocom.setText(txtApellido1.getText());
GUIFactura.CIcomp.setText(txtCedula.getText());
GUIFactura.txtEdadco.setText(txtEdad.getText());
GUIFactura.txtFecha1.setText(txtFecha.getText());
       
GUIFactura.lblImagen.setIcon(lblAuto.getIcon());



if(rbtMercedes.isSelected()){
    GUIFactura.lblimaauto.setIcon(lblMercedes.getIcon());
    GUIFactura.txtmarcaf.setText((String) cbmMercedes.getSelectedItem());
    String aux = (String) cbmMercedes.getSelectedItem();
                if(aux.equals("Mercedes Benzs Clase B B 180D")){
                    GUIFactura.txtPrecio.setText(String.valueOf(auto[0].getPrecio()));
                }
                if(aux.equals("Mercedes Benzs GLA")){
                    GUIFactura.txtPrecio.setText(String.valueOf(auto[1].getPrecio()));
                }
}
if(rbtBMW.isSelected()){
    GUIFactura.lblimaauto.setIcon(jLabel4.getIcon());
    GUIFactura.txtmarcaf.setText((String) cbmBMW.getSelectedItem());
    String aux = (String) cbmBMW.getSelectedItem();
        if(aux.equals("BMW Serie 7")){
            GUIFactura.txtPrecio.setText(String.valueOf(auto[2].getPrecio()));
        }
        if(aux.equals("BMW GRT M3")){
            GUIFactura.txtPrecio.setText(String.valueOf(auto[3].getPrecio()));        
        }
        
    }
if(rbtHyundai.isSelected()){
    GUIFactura.lblimaauto.setIcon(jLabel5.getIcon());
    GUIFactura.txtmarcaf.setText((String) cmbHyundai.getSelectedItem());
    String aux = (String) cmbHyundai.getSelectedItem();
                if(aux.equals("Accent")){
                    GUIFactura.txtPrecio.setText(String.valueOf(auto[4].getPrecio()));
                }
                if(aux.equals("Verna")){
                     GUIFactura.txtPrecio.setText(String.valueOf(auto[5].getPrecio()));
                }

}
GUIFactura.txtColor.setText((String) cmbColor.getSelectedItem());



       
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
    
    String nombre1;
    String apellido1;
    String cedula;
    int edad;
    Fecha fecha;
    String aux;
    ClaseEmpleado empleado = new ClaseEmpleado("00000","Jorge","Proaño","1700235645");
    
    
    try{
        
    aux = txtFecha.getText();
    nombre1= txtNombre1.getText();
    apellido1= txtApellido1.getText();
    cedula = txtCedula.getText();
    edad = Integer.parseInt(txtEdad.getText());
    
    if(txtNombre.getText().equals(empleado.getNombre())){
        if(txtApellido.getText().equals(empleado.getApellido())){
            if(txtCodigo.getText().equals(empleado.getCodigo())){
                //if ()
                ClaseCliente cliente = new ClaseCliente(edad, nombre1, apellido1,cedula);
                crearAutomivil();    
                
            }
        }
    }    
    
    }
    catch(NumberFormatException nfe){
        
            JOptionPane.showMessageDialog(rootPane, "Por favor debe llenar todos las casillas");  
        }
    catch(Exception e){
           JOptionPane.showConfirmDialog(rootPane, "ERROR");
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void rbtMercedesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtMercedesMouseClicked
        // TODO add your handling code here:
        txaInformacion.setText("");
        cbmMercedes.setEnabled(true);
        cmbHyundai.setEnabled(false);
        cbmBMW.setEnabled(false);
    }//GEN-LAST:event_rbtMercedesMouseClicked

    private void rbtBMWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtBMWMouseClicked
        // TODO add your handling code here:
        txaInformacion.setText("");
        cbmMercedes.setEnabled(false);
        cmbHyundai.setEnabled(false);
        cbmBMW.setEnabled(true);
    }//GEN-LAST:event_rbtBMWMouseClicked

    private void rbtHyundaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtHyundaiMouseClicked
        // TODO add your handling code here:
        txaInformacion.setText("");
        cbmMercedes.setEnabled(false);
        cmbHyundai.setEnabled(true);
        cbmBMW.setEnabled(false);
    }//GEN-LAST:event_rbtHyundaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiProyectoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiProyectoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiProyectoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiProyectoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiProyectoFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgMarca;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInformacion;
    private javax.swing.JComboBox<String> cbmBMW;
    private javax.swing.JComboBox<String> cbmMercedes;
    private javax.swing.JComboBox<String> cmbColor;
    private javax.swing.JComboBox<String> cmbHyundai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAuto;
    private javax.swing.JLabel lblBMW;
    private javax.swing.JLabel lblDateExample;
    private javax.swing.JLabel lblHyudai;
    private javax.swing.JLabel lblMercedes;
    private javax.swing.JRadioButton rbtBMW;
    private javax.swing.JRadioButton rbtHyundai;
    private javax.swing.JRadioButton rbtMercedes;
    private javax.swing.JTextArea txaInformacion;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    // End of variables declaration//GEN-END:variables
}
